### ISSUE TITLE
Heroku server-proxy-uri should change the value of host in swagger config

### ISSUE THREAD

**Issue by movadee** [begriffs/postgrest#879]
Hello. I am configuring Swagger and it seems like Heroku server-proxy-uri should change the value of host in swagger config file. Swagger is sending requests to http://0.0.0.0... Please see screenshots. You can test it by going to Swagger http://petstore.swagger.io/ and entering https://amondo-api-demo.herokuapp.com/ for url

<img width="980" alt="screen shot 2017-05-17 at 10 08 21 am" src="https://cloud.githubusercontent.com/assets/8796204/26229825/5d074de4-3c12-11e7-8095-5988bbbde03a.png">
<img width="673" alt="screen shot 2017-05-17 at 10 08 02 am" src="https://cloud.githubusercontent.com/assets/8796204/26229826/5d082458-3c12-11e7-80ed-a6a85343efdd.png">

**Comment by ldesgoui** [comment]
It does change that host value, I'm not sure what you're asking?

**Comment by movadee** [comment]
How come it changes the host value if it's not? Host should be companydomain.com, not 0.0.0.0

**Comment by ldesgoui** [comment]
What did you set `server-proxy-ui` to ?
If you haven't set it, it will use 0.0.0.0:<whatever port you're running on> as a default.

**Comment by movadee** [comment]
my server-proxy-ui is configured. It used to be identical to BUILDPACK_URL.
I changed it to api url, still no luck

**Comment by begriffs** [comment]
Does this behavior happen when you set the value in the postgrest config file locally, or is it purely a Heroku issue?

**Comment by movadee** [comment]
I don't run it locally...

**Comment by begriffs** [comment]
It's pretty easy to do actually. You can download the binary and simply run that, pointing it at the same database instance that the Heroku one uses (unless it's Heroku Postgres which is probably inaccessible from the outside world).

**Comment by movadee** [comment]
I run postgrest locally pointing to the external database and it's working perfectly fine. Host name is proper. I think the problem is in Heroku config

**Comment by begriffs** [comment]
Ohh, do you know what I think it is? The heroku buildpack is looking for an env var called `SERVER_PROXY_URL` ([here](https://github.com/begriffs/postgrest-heroku/blob/master/env-to-config#L13)) whereas our template that powers the Heroku fill-in-the-blanks deployment screen uses `SERVER_PROXY_URI` ([here](https://github.com/begriffs/postgrest/blob/master/app.json#L33)). Postgrest itself uses the uri form rather than url so I need to update the buildpack to match.

**Comment by begriffs** [comment]
OK i updated the heroku buildpack so a redeployment should work now.

**Comment by begriffs** [comment]
@movadee let me know if that fixes things and I'll close this issue.

**Comment by movadee** [comment]
Hello. Sorry for the late reply. I restart all dynos, but problem remains.

**Comment by begriffs** [comment]
Sorry for *my* late reply. We've released postgrest 4.3 and added some improvements to the config parsing. Could you do me a favor and try deploying a fresh instance of your app on heroku with the newer postgrest?

**Comment by movadee** [comment]
Hi Joe! Thank you. I'll try it. Alla

**Comment by ccassan** [comment]
For info, I am getting the same behavior with postgrest 7.0.1 server running in a docker container behind an Nginx reverse-proxy.
`curl -X GET "http://0.0.0.0:8080/pge_activefault" -H  "accept: application/json" -H  "Range-Unit: items"`
I'm guessing it is a problem of set-up of SwaggerUi. Will investigate and let you know.
